### ISSUE TITLE
Fatal Error: Cannot redeclare style_url() within mce_css()

### ISSUE THREAD

**Issue by scottlee** [10up/plugin-scaffold#13]
PHP is throwing a fatal error on L:227 of `functions/core.php` when `mce_css` filter is being run. On the post edit screen for example.

## Steps to reproduce
1. Scaffold a new plugin: `create-10up plugin my-fancy-plugin`
1. Activate the plugin: `wp plugin activate my-fancy-plugin`
1. Attempt to create a new post or page.

## Environment
- WP 4.9.5
- PHP 7.2.1
- Chrome

**Comment by Kluny** [comment]
Duplicate at #22

**Comment by nicholasio** [comment]
It would be great to have this fixed as it basically breaks all new plugin we create using this tool.

**Comment by behzod** [comment]
Note that #14 fixes this issue. It should be just reviewed and merged.
