### ISSUE TITLE
composer.lock should not be in .gitignore

### ISSUE THREAD

**Issue by cmmarslender** [10up/plugin-scaffold#31]
composer.lock file should be committed to our projects so that when we deploy them, we can run composer install and get a very specific set of package versions installed.

I could see maybe not wanting a composer.lock file in the scaffold repo, but we definitely want it in the repos that are generated as part of the scaffolding.

**Comment by daveross** [comment]
It's a holdover from WP Make's templates. I agree it should be removed and we'll just make a point not to add it to the scaffold's repo /cc @timwright12

**Comment by daveross** [comment]
Addressed in 1b164369c81ab317b84707e15b52f67b40b34dd2
