### ISSUE TITLE
PHPUnit test not working

### ISSUE THREAD

**Issue by debabratakarfa** [10up/plugin-scaffold#76]
Getting this error 

`Fatal error: Declaration of WP_Mock\Tools\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp():`

**Comment by debabratakarfa** [comment]
If I add this to composer.json then it working, do the 10up WP Mock [https://github.com/10up/wp_mock] not support for phpunit 7 / 8

`"phpunit/phpunit": "^6",`

**Comment by colis** [comment]
Adding the return type to the `run()` and `setUp()` methods in the `TestCase.php` file will fix the issue, i.e.:

`public function run( \PHPUnit\Framework\TestResult $result = null ): \PHPUnit\Framework\TestResult {`

`public function setUp(): void {`
