### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/plugin-scaffold#90]
It's not obvious the level of support provided for this repo, so let's add some clarification.
- [x] add support level section and badge
- [x] add license file and badge

**Comment by jeffpaul** [comment]
With no license specified, I'm reluctant to add a license file and badge until we confirm the appropriate license to use.

**Comment by jeffpaul** [comment]
@timwright12 you figure MIT license for this repo?

**Comment by timwright12** [comment]
@jeffpaul I'd need to do a little more research, it might need to be the same as WP https://wordpress.org/about/license/

**Comment by jeffpaul** [comment]
@timwright12 the theme and project scaffolds are both licensed MIT, seems like mimicking that (or changing both those to GPLv2) is most logical course?
